### ISSUE TITLE
运行 python train.py出错 

### ISSUE THREAD

**Issue by 12374598858** [wudinaonao/12306CaptchaCrack#2]
请问下这是啥情况  <img src="https://ws1.sinaimg.cn/large/a74cb9c0ly1g1v6v51cknj20mo05saae.jpg">

**Comment by 12374598858** [comment]
<img src="https://ws1.sinaimg.cn/large/a74cb9c0ly1g1v6v51cknj20mo05saae.jpg">

**Comment by 12374598858** [comment]
我 16G 内存，读取分类图片的时候出错

**Comment by wudinaonao** [comment]
> 我 16G 内存，读取分类图片的时候出错

似乎是内存不足的问题, 尝试下路径名不要有中文.

**Comment by wudinaonao** [comment]
> 我 16G 内存，读取分类图片的时候出错

![image](https://user-images.githubusercontent.com/32622524/56503636-561df300-6516-11e9-9b33-ceae40a57a50.png)
我尝试重现问题, 但是我觉得似乎是内存大小的问题, 这是在我机器上跑的时候的内存占用
我的机器配置:
ryzen 1700 32g gtx980ti
可以尝试减小数据集

运行正常
![image](https://user-images.githubusercontent.com/32622524/56503831-eceaaf80-6516-11e9-876c-f689b6912077.png)

**Comment by thefasttime** [comment]
> > 我 16G 内存，读取分类图片的时候出错
> 
> ![image](https://user-images.githubusercontent.com/32622524/56503636-561df300-6516-11e9-9b33-ceae40a57a50.png)
> 我尝试重现问题, 但是我觉得似乎是内存大小的问题, 这是在我机器上跑的时候的内存占用
> 我的机器配置:
> ryzen 1700 32g gtx980ti
> 可以尝试减小数据集
> 
> 运行正常
> ![image](https://user-images.githubusercontent.com/32622524/56503831-eceaaf80-6516-11e9-876c-f689b6912077.png)

我的训练的时候不会使用gpu进行训练 gpu是GTX1060
